# Generated by Django 5.2.4 on 2025-09-16 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_subscribe_author_alter_subscribe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_to_author', to=settings.AUTH_USER_MODEL, verbose_name='На кого подписался'),
        ),
    ]
